### ISSUE TITLE
Consider rollup

### ISSUE THREAD

**Issue by cirocosta** [metal/gulp-metal#12]
hey @mairatma , have you taken a look at http://rollupjs.org/ ? 

> **Tree-shaking?** Normally if you require a module, you import the whole thing. ES2015 lets you just import the bits you need, without mucking around with custom builds. It's a revolution in how we use libraries in JavaScript, and it's happening right now.

Maybe our builds could benefit from that. We're using a lot of es6 code, thus being capable of benefiting of it.

What do you think?

**Comment by mairatma** [comment]
Yep, that could by a nice option for a build, it just doesn't cover all the build types we need right now (like globals and amd). Metal.js can be integrated with any build tools like this though, so I'll take a look when I have some time, it may be worth at least having an example in [metal-examples](https://github.com/metal/metal-examples) showing how to use them together.

**Comment by eduardolundgren** [comment]
They have a globals option there, not sure if its the same globals we have.

**Comment by mairatma** [comment]
It would be nice if we could use it instead for our globals build, I'll check.

**Comment by jbalsas** [comment]
We did create [metal-tools-build-rollup](https://github.com/metal/metal-tools-build-rollup) and actually [integrated it in senna.js](https://github.com/liferay/senna.js/pull/205) although [it didn't make a huge difference](https://github.com/liferay/senna.js/issues/158#issuecomment-313657706).
