### ISSUE TITLE
Allow developers to specify babel plugins to be used

### ISSUE THREAD

**Issue by mairatma** [metal/gulp-metal#14]
This came up on https://github.com/metal/metal-jsx/issues/2. It would be very useful to allow developers to specify other babel plugins, as that way they can easily customize the build without having to rebuilt it from scratch.

**Comment by robframpton** [comment]
Can't developers just use a .babelrc file?

**Comment by jbalsas** [comment]
I think so, at least we have been for a while... closing here.
