### ISSUE TITLE
Allow developers to pass gulp instance to registerTasks method

### ISSUE THREAD

**Issue by robframpton** [metal/gulp-metal#17]
Currently there is no way to pass an instance of `gulp` to the `registerTasks` method which can make it difficult to use these tasks in conjunction with other modules that expose gulp tasks.

For example, in a theme we are trying to implement some of the metal tasks but the `run-sequence` module doesn't have access to the tasks exposed by `gulp-metal`.

What would solve this issue in our use case is passing in our `gulp` instance to `metal.registerTasks` that is then used to register all of the metal tasks.

``` js
metal.registerTasks({
    gulp: gulp
});
```

**Comment by mairatma** [comment]
That makes sense, will do.
