### ISSUE TITLE
Use different test names for different repos/branches in saucelabs

### ISSUE THREAD

**Issue by mairatma** [metal/gulp-metal#22]
Right now, whenever `gulp test:saucelabs` is used, we use the name `MetalJS tests` for the saucelabs suite. That makes it impossible to distinguish between tests run for different branches of a repo, or even for different repos altogether.

We should try to generate different test names for different repo/branch combinations. This can help: https://docs.travis-ci.com/user/environment-variables/

**Comment by jbalsas** [comment]
This was somewhat implemented in https://github.com/metal/gulp-metal/issues/39. I think it's good enough for what we need for now.
