### ISSUE TITLE
Add a complexity task

### ISSUE THREAD

**Issue by mairatma** [metal/gulp-metal#23]
A code complexity task could be really helpful. The idea is to have it measure the code complexity and warn if it exceeds some predefined threshold value.

It's hard to find tools that would work like we need it to though, specially since most of them don't have ES2015 support yet.

One option is to try to use [typhoonjs-escomplex](https://github.com/typhonjs-node-escomplex/typhonjs-escomplex) to build this task.

**Comment by bryceosterhaus** [comment]
https://github.com/metal/gulp-metal/pull/32
