### ISSUE TITLE
Upgrade some dependencies 

### ISSUE THREAD

**Issue by pragmaticivan** [metal/gulp-metal#29]
I'm getting that WARN:

```
→ npm install --save-dev gulp-metal
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

<img width="286" alt="screen shot 2016-12-16 at 11 25 44 am" src="https://cloud.githubusercontent.com/assets/301291/21275604/71237392-c382-11e6-9050-89a4f740014c.png">

Not sure if there's a plan to upgrade some of the dependencies, but just creating this task in case that helps to encourage that.

**Comment by mairatma** [comment]
Thanks @pragmaticivan, I think this will go away if we upgrade `gulp-mocha` to 3.0.0, as that already has the new `minimatch` for example. Not sure what package is requiring `graceful-fs`, but we can investigate and see if we can do something to get that updated too.

**Comment by jonmak08** [comment]
See https://github.com/metal/gulp-metal/pull/59#issuecomment-343559622 for more details.

**Comment by pragmaticivan** [comment]
based on #59 we can close that one
