### ISSUE TITLE
New "lint" task using eslint doesn't complain about lack of semicolon

### ISSUE THREAD

**Issue by mairatma** [metal/gulp-metal#30]
Running `gulp lint` with the new eslint task in metal/metal.js I've noticed that if I remove a semicolon from a required place, lint won't complain about it. Our previous linter complained about that, and it's useful, so we need to make sure the new one is configured to complain as well. 

@bryceosterhaus could you take a look at this? It's probably just missing some configuration.

**Comment by pragmaticivan** [comment]
If that helps: https://gist.github.com/cletusw/e01a85e399ab563b1236
http://eslint.org/docs/rules/semi

Instead using `0`, put `1` as a Warning on `semi` attribute.

**Comment by bryceosterhaus** [comment]
Sent PRs for both gulp-metal and metal.js

https://github.com/metal/gulp-metal/pull/37

https://github.com/metal/metal.js/pull/190

**Comment by eduardolundgren** [comment]
Pulls are merged, thanks.
