### ISSUE TITLE
On SauceLabs testName, use the name of project package running the tests 

### ISSUE THREAD

**Issue by pragmaticivan** [metal/gulp-metal#34]
https://github.com/metal/gulp-metal/blob/88aea16bf1c5561fc9851345a539e85c0e9c6fb9/lib/tasks/test.js#L91

Instead `testName: 'MetalJS tests',`

Try to get the package name of the project using gul-metal. ex: `testName: 'api-js tests',`

**Comment by fernandosouza** [comment]
Hey, @pragmaticivan. I've created a related issue. My idea is to have more custom options. https://github.com/metal/gulp-metal/issues/39

**Comment by jbalsas** [comment]
This was merged and implemented in https://github.com/metal/gulp-metal/issues/39
