### ISSUE TITLE
karma-ievms package version is broken

### ISSUE THREAD

**Issue by ipeychev** [metal/gulp-metal#46]
The `karma-ievms` used in this repository is broken. There is an [issue](https://github.com/xdissent/karma-ievms/issues/10), opened long time ago and still not merged. This error happens on each local machine when we run the tests on IE. Someone created a fix [here](https://github.com/niksy/karma-ievms/tree/browser-decorator) and in order to fix the issue for us, we may do one of these:
1. Change our `package.json` and make `karma-ievms` to look like this: `"karma-ievms": "git+https://github.com/niksy/karma-ievms.git#browser-decorator"` instead `"karma-ievms": "^0.1.0",`.
2. If pointing to an external third party repository is unacceptable, we may fork this repository and apply the same fix. Then we would replace the value of `karma-ievms` in package.json with our forked version.

Please let me know which of these (or some other option) are OK for you.

/cc @eduardolundgren

**Comment by eduardolundgren** [comment]
Option (1) sounds good for me.

**Comment by ipeychev** [comment]
Great, PR is coming!
