### ISSUE TITLE
No way to specify invariant amd module ids

### ISSUE THREAD

**Issue by jbalsas** [metal/gulp-metal#5]
Right now, when executing the `amd` build, module ids are resolved following a relative-path-like strategy.

In our use case, we are configuring a module in our AMD Loader like this:

``` javascript
Loader.addModule(
    {
        dependencies: [],
        exports: 'soy',
        name: 'soyutils',
        path: '/o/frontend-js-web/misc/soyutils.js'
    }
);
```

This way, an amd module could ask for this dependency with the following `define` call:

``` javascript
define(
    "frontend-js-metal-web@1.0.0/metal/src/soy/SoyComponent",
    ['exports', 'module', 'soyutils'],
    function(exports, module, _soyUtils) {
        [...]
    }
);
```

Unfortunately, right now, the process will turn `import soyutils from 'soyutils'` into a `metal/soyutils` module id.

It would be nice to be able to specify that a module id is to be kept as specified somehow.

**Comment by mairatma** [comment]
I forgot to link the commit to this, but this was fixed by https://github.com/metal/gulp-metal/commit/dcd308bf429b27481f6f224a8c4700d559596da8.
